name: PR checks

on:
  pull_request:
    branches: [master]

jobs:
  version-is-unit-incremented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Upgrade pip and install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install packaging
      - name: Check version number
        run: python ./bin/check_version.py

  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Upgrade pip and install doc requirements
        run: pip install -e ".[all,docs]"
      - name: build documentation
        run: |
          cd docs
          make clean
          make html SPHINXOPTS="-W --keep-going -n"

  test-pypi-release:
    name: Build and deploy to test PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install pypa/build
        run: pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        continue-on-error: true
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
